Curse/Curse/Controllers/PlayersController.cs
using Curse.Exceptions;
using Curse.Helpers;
using Curse.Models;
using Curse.Models.Repository;
using Curse.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Curse.Controllers
{
    public class PlayersController : BaseController
    {
        private IPlayerRepository _playerDb;
        private ITeamRepository _teamDb;

        public PlayersController()
        {
            SportsDataContext context = new SportsDataContext();

            _playerDb = new PlayerRepository(context);
            _teamDb = new TeamRepository(context);
        }

        //can be used for mocking and Dependency Injection
        public PlayersController(IPlayerRepository playerDb, ITeamRepository teamDb)
        {
            _playerDb = playerDb;
            _teamDb = teamDb;
        }
        //
        // GET: /Players/
        public ActionResult Index()
        {
            //get a list of all palyers ordered by name
            var players = _playerDb.FindAll().Select(x => new PlayerListViewModel
            {
                ID = x.ID,
                Name = x.Name,
                RBI = x.RBI,
                Homerun = x.HomeRun,
                Average = x.Average,
                TeamName = x.Team.Name ?? "",
                TeamId = x.Team.ID
            })
            .OrderBy(x => x.Name)
            .ToList();

            return View(players);
        }

        public ActionResult Create(int? team)
        {
            var viewmodel = new CreatePlayerViewModel
            {
                RBI = 0,
                HomeRuns = 0,
                Average = 0,
                TeamId = team
            };

            //items to populate in the drop down list
            viewmodel.TeamSelectList = DropDownHelper.BuildTeamSelectList(_teamDb);

            return View(viewmodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreatePlayerViewModel viewmodel, HttpPostedFileBase avatar)
        {
            if (ModelState.IsValid)
            {
                Player player = new Player();
                player.Name = viewmodel.Name;
                player.RBI = viewmodel.RBI;
                player.HomeRun = viewmodel.HomeRuns;
                player.Average = viewmodel.Average;

                player.TeamId = viewmodel.TeamId;

                //add new player to the database, after which player.ID is populated
                _playerDb.Add(player);
                
                if (avatar != null && avatar.ContentLength > 0)
                {
                    AvatarImage image = AvatarUploader.UploadFile2(Server, avatar, player.ID, AvatarTypeEnum.Player);
                    player.AvatarName = image.Name;

                    if (!_playerDb.Update(player))
                    {
                        ModelState.AddModelError("", GenericDatabaseError);
                        viewmodel.TeamSelectList = DropDownHelper.BuildTeamSelectList(_teamDb);
                        return View(viewmodel);
                    }
                }

                return RedirectToAction("Details", new { id = player.ID });
            }

            //this path is reached if the model is initially invalid
            viewmodel.TeamSelectList = DropDownHelper.BuildTeamSelectList(_teamDb);

            return View(viewmodel);
        }

        public ActionResult Details(int id)
        {
            Player model = _playerDb.Find(id);//can cause Exception. Currently bubbles up the the default error handler. It may be better do display a more specific error message in this method.
            if (model == null) return HttpNotFound();

            //PlayerAvatarImage holds the absolute and relative paths to the image
            PlayerAvatarImage image = new PlayerAvatarImage(Server, model.AvatarName);
            PlayerViewModel viewmodel = model.ToPlayerViewModel();
            viewmodel.Avatar = image.Exists ? image.RelativePath : null;
            
            return View(viewmodel);
        }

        public ActionResult Edit(int id)
        {
            var player = _playerDb.Find(id);
            if (player == null) return HttpNotFound();

            PlayerAvatarImage image = new PlayerAvatarImage(Server, player.AvatarName);
            PlayerViewModel viewmodel = player.ToPlayerViewModel();
            viewmodel.Avatar = image.Exists ? image.RelativePath : null;

            viewmodel.TeamSelectList = DropDownHelper.BuildTeamSelectList(_teamDb);

            return View(viewmodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PlayerViewModel viewmodel, HttpPostedFileBase avatar)
        {
            if (ModelState.IsValid)
            {
                Player currentPlayer = _playerDb.Find(viewmodel.ID);
                if (currentPlayer == null) return HttpNotFound();

                currentPlayer.Name = viewmodel.Name;
                currentPlayer.RBI = viewmodel.RBI;
                currentPlayer.HomeRun = viewmodel.HomeRuns;
                currentPlayer.Average = viewmodel.Average;

                currentPlayer.TeamId = viewmodel.TeamId;

                try
                {
                    _playerDb.Update(currentPlayer);

                    if (avatar != null && avatar.ContentLength > 0)
                    {
                        PlayerAvatarImage currentImage = new PlayerAvatarImage(Server, currentPlayer.AvatarName);
                        try
                        {
                            System.IO.File.Delete(currentImage.AbsolutePath);
                        }
                        catch (Exception e)
                        {
                            //
                        }

                        var image = AvatarUploader.UploadFile2(Server, avatar, currentPlayer.ID, AvatarTypeEnum.Player);

                        currentPlayer.AvatarName = image.Name;
                        _playerDb.Update(currentPlayer);//updates the new image file name
                    }


                    return RedirectToAction("Details", new { id = currentPlayer.ID });
                }
                catch (CustomExceptionBase e)
                {
                    ModelState.AddModelError("", e.Message);
                }
                catch (Exception e)
                {
                    //log error
                    ModelState.AddModelError("", GenericErrorMessage);
                }
            }

            viewmodel.TeamSelectList = DropDownHelper.BuildTeamSelectList(_teamDb);

            return View(viewmodel);
        }

        public ActionResult Delete(int id)
        {
            var player = _playerDb.Find(id);
            if (player == null) return HttpNotFound();

            PlayerAvatarImage image = new PlayerAvatarImage(Server, player.AvatarName);
            PlayerViewModel viewmodel = player.ToPlayerViewModel();
            viewmodel.Avatar = image.Exists ? image.RelativePath : null;

            return View(viewmodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(PlayerViewModel viewmodel)
        {
            try
            {
                var player = _playerDb.Find(viewmodel.ID);
                if (player == null) return HttpNotFound();

                PlayerAvatarImage image = new PlayerAvatarImage(Server, player.AvatarName);

                try
                {
                    System.IO.File.Delete(image.AbsolutePath);
                }
                catch (Exception e)
                {
                    //log error...
                    //continue this method
                }
            }  
            catch (Exception e)
            {
                //log error
                ModelState.AddModelError("", GenericErrorMessage);
                return View(viewmodel);
            }

            try
            {
                _playerDb.Delete(viewmodel.ID);
            }
            catch (Exception e)
            {
                //log error, redirect to error view isntead
                ModelState.AddModelError("", GenericDatabaseError);
                return View(viewmodel);
            }

            return RedirectToAction("Index");
        }

    }
}

Curse/Curse/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Curse.Models;
using Curse.Models.ViewModels;
using Curse.Models.Repository;
using System.IO;
using Curse.Helpers;
using Curse.Exceptions;

namespace Curse.Controllers
{
    //[Authorize] authorization/authenication not used in this demo
    public class TeamsController : BaseController
    {
        private ITeamRepository _teamDb;
        private IPlayerRepository _playerDb;

        public TeamsController()
        {
            SportsDataContext context = new SportsDataContext();

            _teamDb = new TeamRepository(context);
            _playerDb = new PlayerRepository(context);
        }

        //allow for Dependency Injection and Mocking
        public TeamsController(ITeamRepository teamDdb,IPlayerRepository playerDb)
        {
            _teamDb = teamDdb;
            _playerDb = playerDb;
        }
        //
        // GET: /Teams/
        public ActionResult Index()
        {
            //return a list of teams sorted by team name
            var teams = _teamDb.FindAll().Select(x => new TeamListViewModel{
              ID = x.ID,
              Name = x.Name,
              PlayerCount = x.Players.Count()
            })
            .OrderBy(x => x.Name)
            .ToList();
            
            return View(teams);
        }

        public ActionResult Create()
        {
            return View(new CreateTeamViewModel());
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]//prevents CSRF attacks
        public ActionResult Create(CreateTeamViewModel viewmodel, HttpPostedFileBase avatar)
        {
            if (ModelState.IsValid)
            {
                try
                {
                        Team team = new Team { Name = viewmodel.Name };

                        _teamDb.Add(team);

                        //if an image has been provided then upload it
                        if (avatar != null && avatar.ContentLength > 0)
                        {
                                                     
                            AvatarImage image = AvatarUploader.UploadFile2(Server, avatar, team.ID, AvatarTypeEnum.Team);

                            team.AvatarName = image.Name; 

                            if (!_teamDb.Update(team)) //update the avatar path after database has set PK
                            {
                                return Content("An error has occurred on the server");//just temporary, create error view
                            }
                        }
                    
                        return RedirectToAction("Details", new { id = team.ID });
                }
                catch (Exception e)
                {
                    //log exception
                    //return error message to user
                    ModelState.AddModelError("", "Exception occured on the server");
                }
                
            }

            return View();
        }

        public ActionResult Details(int id)
        {
            var team = _teamDb.Find(id);
            if (team == null) return HttpNotFound();

            TeamAvatarImage image = new TeamAvatarImage(Server, team.AvatarName);//find out the correct path for the avatar (if there is one)
            TeamViewModel viewmodel = new TeamViewModel { ID = id, Name = team.Name };
            viewmodel.Avatar = image.Exists ? image.RelativePath : null;

            //build the list of players for this team to display
            viewmodel.PlayerList = _playerDb.FindAll().Where(x => x.TeamId == team.ID).Select(x => new PlayerViewModel { Name = x.Name, ID = x.ID }).ToList();

            return View(viewmodel);
        }

        public ActionResult Edit(int id)
        {
            var team = _teamDb.Find(id);
            if (team == null) return HttpNotFound();

            TeamAvatarImage image = new TeamAvatarImage(Server, team.AvatarName);
            TeamViewModel viewmodel = new TeamViewModel { ID = id, Name = team.Name };
            viewmodel.Avatar = image.Exists ? image.RelativePath : null;

            return View(viewmodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TeamViewModel viewmodel, HttpPostedFileBase avatar)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Team team = _teamDb.Find(viewmodel.ID);
                    if (team == null) return HttpNotFound();

                    team.Name = viewmodel.Name;

                    if (!_teamDb.Update(team))
                    {
                        //log error...
                        ModelState.AddModelError("", "An error occurred updating the use information");
                        return View(viewmodel);
                    }

                    //if an image has been provided then upload it
                    if (avatar != null && avatar.ContentLength > 0)
                    {
                        try
                        {
                            //delete the current avatar image
                            TeamAvatarImage currentImage = new TeamAvatarImage(Server, team.AvatarName);
                            System.IO.File.Delete(currentImage.AbsolutePath);
                        }
                        catch (CustomExceptionBase e)
                        {//safe error message for user
                            ModelState.AddModelError("", e.Message);
                            return View(viewmodel);
                        }
                        catch (Exception e)
                        {
                            //log error
                            ModelState.AddModelError("", "An error has occurred on the server.");
                            return View(viewmodel);
                        }

                        AvatarImage image = AvatarUploader.UploadFile2(Server, avatar, team.ID, AvatarTypeEnum.Team);

                        team.AvatarName = image.Name;
                        _teamDb.Update(team);

                    }

                    return RedirectToAction("Details", new { id = team.ID });
                }
                catch (CustomExceptionBase e)
                {
                    ModelState.AddModelError("", e.Message);
                }
                catch (Exception e)
                {
                    //log exception
                    //return error message to user
                    ModelState.AddModelError("", "Exception occured on the server");
                }

            }

            return View(viewmodel);
        }

        public ActionResult Delete(int id)
        {
            var team = _teamDb.Find(id);
            if (team == null) return HttpNotFound();

            TeamAvatarImage image = new TeamAvatarImage(Server, team.AvatarName);

            TeamViewModel viewmodel = new TeamViewModel { ID = id, Name = team.Name };
            viewmodel.Avatar = image.Exists ? image.RelativePath : null;

            return View(viewmodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(TeamViewModel viewmodel)
        {
            try
            {
                var team = _teamDb.Find(viewmodel.ID);
                if (team == null) return HttpNotFound();

                //if there is a current image then delete it
                if (!String.IsNullOrEmpty(team.AvatarName))
                {
                    TeamAvatarImage image = new TeamAvatarImage(Server, team.AvatarName);
                    System.IO.File.Delete(image.AbsolutePath);
                }
            }
            catch (Exception e)
            {
                //log error...
                ModelState.AddModelError("", GenericErrorMessage);
                return View(viewmodel);
            }

            try
            {
                var playersOnTeam = _playerDb.FindAll().Where(x => x.TeamId == viewmodel.ID).ToList();

                playersOnTeam.ForEach(x => 
                    {                        
                        try
                        {
                            //delete this player from the database
                            _playerDb.Delete(x.ID);

                            //delete the players avatar
                            PlayerAvatarImage image = new PlayerAvatarImage(Server, x.AvatarName);
                            if(!String.IsNullOrEmpty(x.AvatarName))System.IO.File.Delete(image.AbsolutePath);
                        }
                        catch (Exception e)
                        {
                            //log error...
                        }
                    });//delete all players on the team first
                _teamDb.Delete(viewmodel.ID);
            }
            catch (Exception e)
            {
                //log error
                return Content("Error");//temp
            }

            return RedirectToAction("Index");
        }

    }
}

Curse/Curse/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/SportsStats.css")
        <link href="~/Content/SportsStats.css" rel="stylesheet" type="text/css" />
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Baseball Sports Stats", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Team List", "Index", "Teams")</li>
                            <li>@Html.ActionLink("Player List", "Index", "Players")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Brandon Laseter Sports Stats</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)

        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>
    </body>
</html>

Curse/Curse/Views/Shared/_Summary.cshtml
@model Curse.Models.ViewModels.SummaryViewModel

<table class="summary" style="float:right">
    <tr>
        <th>
            @Html.ActionLink("Total Teams", "Index", "Teams")
        </th>
        <td>@Model.TotalTeams</td>
    </tr>
    <tr>
        <th>@Html.ActionLink("Total Players", "Index", "Players")</th>
        <td>@Model.TotalPlayers</td>
    </tr>
</table>

@if(Model.HasAnyPlayers)
{
<table class="summary">
    <tr>
        <th></th>
        <th>Name</th>
        <th>Team</th>
        <th>Value</th>
    </tr>

    @*I could probably created helper method to enforce the DRY strategy here*@
    @if (Model.PlayerWithMostRBI != null)
    {
    <tr>
        <th>Player with Most RBIs</th>
        <td>
            @Html.ActionLink(Model.PlayerWithMostRBI.Name, "Details", "Players", new { id = Model.PlayerWithMostRBI.ID}, null)
        </td>
        <td>
            @if(@Model.PlayerWithMostRBI.TeamName !=null)
            {
                @Html.ActionLink(Model.PlayerWithMostRBI.TeamName, "Details", "teams", new { id = Model.PlayerWithMostRBI.TeamId}, null)
            }
        </td>
        <td>
            @Html.DisplayFor(x =>x.PlayerWithMostRBI.RBI)

        </td>
    </tr>
    }

     @if (Model.PlayerWithMostHomeRuns != null)
    {
    <tr>
        <th>Player with Most Home Runs</th>
        <td>
            @Html.ActionLink(Model.PlayerWithMostHomeRuns.Name, "Details", "Players", new { id = Model.PlayerWithMostHomeRuns.ID}, null)
        </td>
        <td>
            @if (Model.PlayerWithMostHomeRuns.TeamName != null)
            {
                @Html.ActionLink(Model.PlayerWithMostHomeRuns.TeamName, "Details", "teams", new { id = Model.PlayerWithMostHomeRuns.TeamId}, null)
            }
        </td>
        <td>
            @Html.DisplayFor(x =>x.PlayerWithMostHomeRuns.HomeRuns)
        </td>
    </tr>
    }

     @if (Model.PlayerWithHighestAverage != null)
    {
    <tr>
        <th>Player with Best Average</th>
        <td>
            @Html.ActionLink(Model.PlayerWithHighestAverage.Name, "Details", "Players", new { id = Model.PlayerWithHighestAverage.ID}, null)
        </td>
        <td>
            @if(Model.PlayerWithHighestAverage.TeamName != null)
            {
                @Html.ActionLink(Model.PlayerWithHighestAverage.TeamName, "Details", "teams", new { id = Model.PlayerWithHighestAverage.TeamId}, null)
            }
        </td>
        <td>
            @Html.DisplayFor(x =>x.PlayerWithHighestAverage.Average)

        </td>
    </tr>
    }
</table>
}